### ISSUE TITLE
MixedCoilSet.save bug

### ISSUE THREAD

**Issue by ddudt** [PlasmaControl/DESC#1013]
There is an issue preventing a `MixedCoilSet` from saving when it contains a mix of both coil sets and individual coils. Minimal working example on `master`: 
```
from desc.coils import FourierPlanarCoil, CoilSet, MixedCoilSet

coil = FourierPlanarCoil()
coils = CoilSet.linspaced_angular(coil)
coilset = MixedCoilSet((coil, coils))

coilset.save("coilset.h5")
```
Traceback: 
```
/home/dudt/DESC/desc/io/hdf5_io.py:314: RuntimeWarning: Save attribute '_current' was not saved as it does not exist.
  warnings.warn(
Traceback (most recent call last):
  File "/home/dudt/DESC/debug.py", line 7, in <module>
    coilset.save("coilset.h5")
  File "/home/dudt/DESC/desc/io/equilibrium_io.py", line 248, in save
    writer.write_obj(self)
  File "/home/dudt/DESC/desc/io/hdf5_io.py", line 312, in write_obj
    loc.create_dataset(attr, data=data, compression=compression)
  File "/home/dudt/.local/lib/python3.10/site-packages/h5py/_hl/group.py", line 183, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/home/dudt/.local/lib/python3.10/site-packages/h5py/_hl/dataset.py", line 46, in make_new_dset
    data = array_for_new_object(data, specified_dtype=dtype)
  File "/home/dudt/.local/lib/python3.10/site-packages/h5py/_hl/base.py", line 118, in array_for_new_object
    data = np.asarray(data, order="C", dtype=as_dtype)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part. 
```

Probably unrelated, but there is also the warning stating that the "_current" attribute is not saved. When saving a `CoilSet` this warning is also thrown, although it appears the currents are in fact saved properly.

**Comment by dpanici** [comment]
I dont quite understand the issue yet but maybe this sort of thing could help: https://gist.github.com/nirum/b119bbbd32d22facee3071210e08ecdf
