### ISSUE TITLE
NERSC Slurm script

### ISSUE THREAD

**Issue by mohawk811** [PlasmaControl/DESC#1325]
```
2024-10-24 17:38:10.460311: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
CUDA backend failed to initialize: FAILED_PRECONDITION: No visible GPU devices. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
Traceback (most recent call last):
  File "/global/u1/m/mh3705/scratch/quasi_pol/desc_10_21_24/geo_aspect_scan_gpu/quasi_pol.py", line 50, in <module>
    set_device('gpu')
  File "/global/u1/m/mh3705/scratch/DESC/desc/__init__.py", line 94, in set_device
    devices = nvgpu.gpu_info()
  File "/global/homes/m/mh3705/.conda/envs/desc_gpu-env/lib/python3.9/site-packages/nvgpu/__init__.py", line 13, in gpu_info
    lines = _run_cmd(['nvidia-smi'])
  File "/global/homes/m/mh3705/.conda/envs/desc_gpu-env/lib/python3.9/site-packages/nvgpu/__init__.py", line 32, in _run_cmd
    output = subprocess.check_output(cmd)
  File "/global/homes/m/mh3705/.conda/envs/desc_gpu-env/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/global/homes/m/mh3705/.conda/envs/desc_gpu-env/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['nvidia-smi']' returned non-zero exit status 6.
srun: error: nid003677: task 0: Exited with exit code 1
srun: Terminating StepId=32150174.0
```

Would it be possible if someone could share their slurm script for using a gpu for DESC on NERSC? I tried a number of things but this is the error I get from trying. I feel confident that my installation is fine from running the tests listed on the documentation.

```#!/bin/bash
#SBATCH --nodes=1
#SBATCH --image=ghcr.io/nvidia/jax:jax
#SBATCH --time=1-00:00:00
#SBATCH --constraint=gpu
#SBATCH --qos regular
#SBATCH --account=m4680
#SBATCH --output=log.out
#SBATCH --error=log.err

module load conda
conda activate desc_gpu-env
module load cudatoolkit/12.2
module load cudnn/8.9.3_cuda12
srun --module=gpu --image=ghcr.io/nvidia/jax:jax /global/homes/m/mh3705/.conda/envs/desc_gpu-env/bin/python quasi_pol.py
'''

This is my current slurm script.

**Comment by rahulgaur104** [comment]
Hi @mohawk811,
Have you tried the instructions given here to [install DESC on Perlmutter](https://desc-docs.readthedocs.io/en/latest/installation.html#perlmutter-nersc)?
If not, please try that first instead of using a jax image.

**Comment by mohawk811** [comment]
Yes I followed those instructions and when I test the installation everything loads in fine

**Comment by rahulgaur104** [comment]
Ok, then use the following slurm script and you should be able to run a job.


```
#!/bin/bash

#SBATCH --qos=regular
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=gpu&hbm80g
#SBATCH --gpus 1
#SBATCH --mem=32G
#SBATCH --account=m4505_g
#SBATCH --time=03:25:00

export XLA_PYTHON_CLIENT_MEM_FRACTION=.93

XLA_PYTHON_CLIENT_MEM_FRACTION=.93

module load cudatoolkit/12.2;\
module load cudnn/8.9.3_cuda12;\

module load python;\

conda activate desc-env;\

python3 driver_ball_omni.py
```

**Comment by mohawk811** [comment]
Hi Just to follow up

````
#!/bin/bash

#SBATCH --qos=regular
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --constraint=gpu&hbm80g
#SBATCH --gpus 1
#SBATCH --mem=32G
#SBATCH --time=03:25:00
#SBATCH --account=m4680
#SBATCH --output=log.out
#SBATCH --error=log.err

export XLA_PYTHON_CLIENT_MEM_FRACTION=.93

XLA_PYTHON_CLIENT_MEM_FRACTION=.93

module load cudatoolkit/12.2;\
module load cudnn/8.9.3_cuda12;\

module load python;\

conda activate desc_gpu-env;\

python quasi_pol.py


```
and this is the output I get:

```
2024-10-25 18:31:43.861324: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
CUDA backend failed to initialize: FAILED_PRECONDITION: No visible GPU devices. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/global/u1/m/mh3705/scratch/DESC/desc/__init__.py:113: UserWarning: CUDA_VISIBLE_DEVICES= did not match any physical GPU (id=['0', '1', '2', '3']), falling back to CPU
  warnings.warn(
slurmstepd: error: *** JOB 32200902 ON nid008216 CANCELLED AT 2024-10-26T04:55:55 DUE TO TIME LIMIT ***
```

Do you have any advice on how to resolve this?

**Comment by rahulgaur104** [comment]
Can you try

` #SBATCH --constraint=gpu
`
?

**Comment by mohawk811** [comment]
```
2024-10-27` 13:34:37.415121: E external/xla/xla/stream_executor/cuda/cuda_driver.cc:282] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
CUDA backend failed to initialize: FAILED_PRECONDITION: No visible GPU devices. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/global/u1/m/mh3705/scratch/DESC/desc/__init__.py:113: UserWarning: CUDA_VISIBLE_DEVICES= did not match any physical GPU (id=['0', '1', '2', '3']), falling back to CPU
  warnings.warn(
```
To solve this do I use "Set TF_CPP_MIN_LOG_LEVEL=0" If so how should I feed it in?

**Comment by dpanici** [comment]
@ddudt please post your NERSC script here?
@mohawk811 can you post your python script here so we can check you are setting device properly?

**Comment by rahulgaur104** [comment]
@mohawk811 
> To solve this do I use "Set TF_CPP_MIN_LOG_LEVEL=0" If so how should I feed it in?
To do that set 
`
export TF_CPP_MIN_LOG_LEVEL=0
`
in the Slurm job file. But that won't fix your problem. 

Can you just initialize a python environment and check if you can 
```
from desc import set_device
set_device("gpu")
```

**Comment by mohawk811** [comment]
This is just my testing on my node on perlmutter

**Comment by mohawk811** [comment]
```
from desc import set_device
import numpy as np
from desc.equilibrium import EquilibriaFamily, Equilibrium
from desc.grid import LinearGrid, QuadratureGrid
from desc.objectives import (
    CurrentDensity,
    ObjectiveFunction,
    Omnigenity,
)
from desc.geometry import FourierRZToroidalSurface
from desc.equilibrium import Equilibrium
from desc.continuation import solve_continuation_automatic
import numpy as np
import matplotlib.pyplot as plt
import desc.io
from desc.grid import LinearGrid, ConcentricGrid
from desc.objectives import (
    ObjectiveFunction,
    FixBoundaryR,
    FixBoundaryZ,
    FixPressure,
    FixIota,
    FixPsi,
    AspectRatio,
    ForceBalance,
    QuasisymmetryBoozer,
    QuasisymmetryTwoTerm,
    QuasisymmetryTripleProduct,    GenericObjective,
    RotationalTransform,
    Elongation,
    FixCurrent,
)
from desc.optimize import Optimizer
from desc.plotting import (
    plot_grid,
    plot_boozer_modes,
    plot_boozer_surface,
    plot_qs_error,
    plot_boundaries,
    plot_boundary,
    plot_1d,
    plot_2d,
    plot_3d,
    plot_section,
)
import sys
import os
from desc import set_device
set_device('gpu')
from desc.equilibrium import Equilibrium
def run_qp_step(k,a, eq):

    # create grid where we want to minimize QS error. Here we do it on 3 surfaces
    grid = LinearGrid(
        M=eq.M_grid, N=eq.N_grid, NFP=eq.NFP, rho=np.array([.2,.6,1.0]), sym=True
    )

    # we create an ObjectiveFunction, in this case made up of multiple objectives
    # which will be combined in a least squares sense
    objective = ObjectiveFunction(
        (
            AspectRatio(eq=eq, grid=grid, target=a, weight=1),
            GenericObjective("kappa_g", thing=eq, grid=grid, target=0),
           # QuasisymmetryTwoTerm(eq=eq, grid=grid, helicity=(0, eq.NFP)),
            RotationalTransform(eq=eq, grid=grid, bounds=(.15,5)),
            Elongation(eq=eq, grid=grid, target=2, weight=1),
           # ForceBalance(eq=eq, grid=grid, bounds=(1e-10,1e-3),weight=1),
           # CurrentDensity(eq=eq,grid=grid,target=0)
        ),
    )

    R_modes = np.vstack(
        (
            [0, 0, 0],
            eq.surface.R_basis.modes[
                np.max(np.abs(eq.surface.R_basis.modes), 1) > k, :
            ],
        )
    )
    Z_modes = eq.surface.Z_basis.modes[
        np.max(np.abs(eq.surface.Z_basis.modes), 1) > k, :
    ]

    constraints = (
                              ForceBalance(eq=eq), #get rid of force balance and pressure
        FixBoundaryR(eq=eq, modes=R_modes),
        FixBoundaryZ(eq=eq, modes=Z_modes),
        FixPressure(eq=eq),
        FixPsi(eq=eq),
        AspectRatio(eq=eq, target=a),
        Elongation(eq=eq, target=2),
        ForceBalance(eq=eq, grid=grid, bounds=(1e-10,1e-4)),
        FixCurrent(eq=eq),
        RotationalTransform(eq=eq, bounds=(.15,5)),
        # fix major radius
    )
    # this is the default optimizer, which re-solves the equilibrium at each step
    optimizer = Optimizer("lsq-auglag")

    eq_new, history = eq.optimize(
        objective=objective,
        constraints=constraints,
        optimizer=optimizer,
        maxiter=1000,  # we don't need to solve to optimality at each multigrid step
        verbose=3,
        copy=True,  # don't modify original, return a new optimized copy
        options={
            # Sometimes the default initial trust radius is too big, allowing the
            # optimizer to take too large a step in a bad direction. If this happens,
            # we can manually specify a smaller starting radius. Each optimizer has a          # See the documentation for more info.
            "initial_trust_ratio": 1.0,
        },
    )
    return eq_new

for a in range(2,20):
    for i in range(5):
        if i==0:
            #eq = desc.io.load("eq_opt_geodesic_22.h5")
            #eq.solve()
            Psi = 0.023050438527737336
            surf = FourierRZToroidalSurface.from_qp_model(
            major_radius=1,
            aspect_ratio=a, #scan over
            elongation=2,
            mirror_ratio=0.1, #Scan over add objective target
            torsion=0, #independent
            NFP=2, #Scan over
            sym=True,
            positive_iota=True)
            eq = Equilibrium(L=i+2, M=i+2, N=i+2, Psi=Psi, surface=surf)
            eq.solve()

```

**Comment by rahulgaur104** [comment]
Can you try running the above script on the login node after adding 

```
from desc import set_device
set_device("gpu")
```

at the very top of that script?

**Comment by mohawk811** [comment]
Putting this at the start of my script fixed the issue. Thank you so much! :)

**Comment by rahulgaur104** [comment]
Glad to hear it. Closing the issue now.
