### ISSUE TITLE
Inaccurate concentric grid due to round-off at high N_grid values

### ISSUE THREAD

**Issue by patil3** [PlasmaControl/DESC#207]
I noticed that if I use N_grid = 30, the grid module runs into an error at line 710, which reads:
`z = np.arange(0, 2 * np.pi / NFP, dz)`
The trace reads:
`Traceback (most recent call last):
  File "descrun.py", line 6, in <module>
    eq1.change_resolution(N_grid=30)
  File "/srv/home/sapatil/.conda/envs/descenv/lib/python3.10/site-packages/desc/equilibrium.py", line 319, in change_resolution
    self._set_grid()
  File "/srv/home/sapatil/.conda/envs/descenv/lib/python3.10/site-packages/desc/equilibrium.py", line 176, in _set_grid
    self._grid = ConcentricGrid(
  File "/srv/home/sapatil/.conda/envs/descenv/lib/python3.10/site-packages/desc/grid.py", line 559, in __init__
    self._nodes, self._weights = self._create_nodes(
  File "/srv/home/sapatil/.conda/envs/descenv/lib/python3.10/site-packages/desc/grid.py", line 672, in _create_nodes
    nodes = np.stack([r, t, z]).T
  File "<__array_function__ internals>", line 5, in stack
  File "/srv/home/sapatil/.local/lib/python3.10/site-packages/numpy/core/shape_base.py", line 426, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape`

I found that this is a result of round-off error in `dz` from line 709:
`dz = 2 * np.pi / (NFP * (2 * N + 1))`
One solution is to use np.linspace at line 710:
`z = np.linspace(0, 2 * np.pi / NFP, 2 * N + 2)[:-1]`
I have attached a section of the source code (v 0.4.9) that creates the grid. This can be used as an independent script. The issue can be reproduced when N=30 or higher.
This was a minor bug, but I thought it may be worth reporting.
[conc_grid.txt](https://github.com/PlasmaControl/DESC/files/8951477/conc_grid.txt)

**Comment by patil3** [comment]
Great! Glad to be of help.
