### ISSUE TITLE
Fix Bug in DESC Scalar Routines

### ISSUE THREAD

**Issue by dpanici** [PlasmaControl/DESC#232]
When using any of the DESC custom scalar routines (``'dogleg'``, ``'subspace'``, ``'dogleg-bfgs'``,
          ``'subspace-bfgs'``), if tolerances are hit before a step that lowers the objective function can be found, it will not save `allx` in the `result` dict, resulting in a `KeyError`

below is output from running `SOLOVEV` input file but changing optimizer to `subspace`
```
Starting optimization
   Iteration     Total nfev        Cost      Cost reduction    Step norm     Optimality
       0              2         2.2051e+12      1.66e+06       7.91e-07       1.14e+12
Optimization terminated successfully.
`ftol` condition satisfied.
`xtol` condition satisfied.
         Current function value: 2.205e+12
         Iterations: 1
         Function evaluations: 2
         Gradient evaluations: 2
         Hessian evaluations: 2
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/dpanici/DESC/desc/__main__.py", line 62, in <module>
    main(sys.argv[1:])
  File "/home/dpanici/DESC/desc/__main__.py", line 42, in main
    equil_fam.solve_continuation(
  File "/home/dpanici/DESC/desc/equilibrium.py", line 923, in solve_continuation
    equil.solve(
  File "/home/dpanici/DESC/desc/equilibrium.py", line 361, in solve
    result = optimizer.optimize(
  File "/home/dpanici/DESC/desc/optimize/optimizer.py", line 477, in optimize
    for x_reduced in result["allx"]:
KeyError: 'allx'
```

**Comment by dpanici** [comment]
reason was just a typo in the code
