### ISSUE TITLE
Project doesn't work when N_grid = 0

### ISSUE THREAD

**Issue by pkim1818** [PlasmaControl/DESC#389]
When trying to do a projection in Z when N_grid = 0, there's an error because the matrix A that should be used is an empty dictionary. A should be initialized so that it returns an array of zeros (or something similar).
The following leads to an error.
```
import desc.io
import numpy as np
from desc.compute import get_transforms
from desc.grid import ConcentricGrid

eq = desc.io.load('desc/examples/DSHAPE_output.h5')[-1]
data_keys = ["F_rho","|grad(rho)|","sqrt(g)","F_helical","|e^helical|"]
grid = ConcentricGrid(L=eq.L_grid,M=eq.M_grid,N=eq.N_grid,NFP=eq.NFP,sym=eq.sym,axis=False,node_pattern=eq.node_pattern)
tr = get_transforms(data_keys,eq,grid)
f = np.ones(grid.num_nodes)

print(tr["Z"].project(f))
```

The error being
```
Traceback (most recent call last):
  File "/scratch/gpfs/pk2354/DESC_force/test_project.py", line 12, in <module>
    print(tr["Z"].project(f))
  File "/scratch/gpfs/pk2354/DESC_force/desc/transform.py", line 606, in project
    return jnp.matmul(A.T, y)
AttributeError: 'dict' object has no attribute 'T'
```

**Comment by f0uriest** [comment]
Ahhh it's because Z doesn't enter the equations anywhere by itself, only through derivatives of Z. So when the transform is built we skip computing the matrices for doing the transform of Z. I'll figure out a fix.
