### ISSUE TITLE
OmnigenousField.change_resolution() returns error

### ISSUE THREAD

**Issue by landreman** [PlasmaControl/DESC#788]
Using branch `dd/omnigenity`, minimal example:
~~~~py
import numpy as np
from desc.magnetic_fields import OmnigenousField

nfp = 4
field = OmnigenousField(
    L_well=0,  # radial resolution of B_lm parameters
    M_well=3,  # number of spline knots on each flux surface
    L_shift=0,  # radial resolution of x_lmn parameters
    M_shift=0,  # eta resolution of x_lmn parameters
    N_shift=0,  # alpha resolution of x_lmn parameters
    NFP=nfp,  # number of field periods; should always be equal to Equilibrium.NFP
    helicity=(0, nfp),  # helicity for poloidally closed |B| contours
    B_lm=np.array([0.8, 1.0, 1.2]),
)

field.change_resolution(M_well=10)
~~~~
Present output:
~~~~
DESC version 0.10.2+452.g15925f7b.dirty,using JAX backend, jax version=0.4.14, jaxlib version=0.4.14, dtype=float64
Using device: CPU, with 11.64 GB available memory
Traceback (most recent call last):
  File "/Users/mattlandreman/work23/./20231205-02-desc_omni_change_resolution_bug.py", line 18, in <module>
    field.change_resolution(M_well=10)
  File "/Users/mattlandreman/DESC/dd-omnigenity/desc/magnetic_fields.py", line 1763, in change_resolution
    self.L, self.M, self.N, NFP=self.NFP, sym="cos(t)"
AttributeError: 'OmnigenousField' object has no attribute 'L'
~~~~
If I update that line 1763 to
~~~~py
    self.L_shift, self.M_shift, self.N_shift, NFP=self.NFP, sym="cos(t)"
~~~~
there is a different error:
~~~~
DESC version 0.10.2+452.g15925f7b.dirty,using JAX backend, jax version=0.4.14, jaxlib version=0.4.14, dtype=float64
Using device: CPU, with 11.64 GB available memory
Traceback (most recent call last):
  File "/Users/mattlandreman/work23/./20231205-02-desc_omni_change_resolution_bug.py", line 18, in <module>
    field.change_resolution(M_well=10)
  File "/Users/mattlandreman/DESC/dd-omnigenity/desc/magnetic_fields.py", line 1768, in change_resolution
    old_well = self.B_lm.reshape((-1, self.M_well))
ValueError: cannot reshape array of size 3 into shape (10)
~~~~

**Comment by ddudt** [comment]
This should be fixed now with commit [2cc16ad](https://github.com/PlasmaControl/DESC/pull/535/commits/2cc16add2fcf0f1fa2561e67fcc12ec41ad13cc4)

It appears that when changing the number of spline knots `M_well` the shape of the magnetic well does change slightly. In the test case I used, the change in $|B|$ is on the order of 0.5%, but this could be higher for other cases and will affect the omnigenity errors slightly. 

Here are comparison plots of how the well changes for the test case I used: 
![image](https://github.com/PlasmaControl/DESC/assets/33005725/646f550c-da0a-4d78-9a46-07f718769858)
![image](https://github.com/PlasmaControl/DESC/assets/33005725/9de053a0-19f9-43e0-94c3-37f15e7b7424)

**Comment by landreman** [comment]
Great, thanks!
