### ISSUE TITLE
ValueError: operands could not be broadcast together with shapes (26,196) (26,130)

### ISSUE THREAD

**Issue by jonathanschilling** [PlasmaControl/DESC#98]
Hi,
when running the W7-X example case (input file `examples/W7X`), DESC crashes.
I am using the tag `v0.4.7` of DESC using the following module setup on the [Cobra cluster of MPCDF](https://docs.mpcdf.mpg.de/doc/computing/cobra-user-guide.html):

```
  1) cuda/11.0            2) anaconda/3/2020.02
```

I run DESC via a custom Python script:

```python
desc_path = "/u/jons/src/DESC"
import sys
if not desc_path in sys.path:
    sys.path.insert(0, desc_path)

# before anything else, make sure to use GPU
from desc import set_device
set_device("gpu")

# from here on, one can import anything else from DESC

input_filename = desc_path+"/examples/DESC/W7X"
output_filename = input_filename+"_output.h5"

from desc.io import InputReader
ir = InputReader()
inputs = ir.parse_inputs(fname=input_filename)

import desc
print(desc.BANNER)
print("Reading input from {}".format(input_filename))
print("Outputs will be written to {}".format(output_filename))

from desc.backend import use_jax
from desc.equilibrium import EquilibriaFamily

# initialize
equil_fam = EquilibriaFamily(inputs)

# solve equilibrium
equil_fam.solve_continuation(verbose=True, checkpoint_path=output_filename)
```

After/During the first continuation step, DESC crashes and I get the following stack trace:

```
Traceback (most recent call last):
  File "/u/jons/src/desc_standalone.py", line 32, in <module>
    equil_fam.solve_continuation(verbose=True, checkpoint_path=output_filename)
  File "/u/jons/src/DESC/desc/equilibrium.py", line 827, in solve_continuation
    N_grid=self.inputs[ii]["N_grid"],
  File "/u/jons/src/DESC/desc/equilibrium.py", line 321, in change_resolution
    self.objective = self.objective.name
  File "/u/jons/src/DESC/desc/equilibrium.py", line 421, in objective
    self.objective = objective
  File "/u/jons/src/DESC/desc/equilibrium.py", line 402, in objective
    elif isinstance(objective, ObjectiveFunction) and objective.eq(self.objective):
  File "/u/jons/src/DESC/desc/io/equilibrium_io.py", line 197, in eq
    return equals(dict1, dict2)
  File "/u/jons/src/DESC/desc/utils.py", line 247, in equals
    return all(equals(a[key], b[key]) for key in a)
  File "/u/jons/src/DESC/desc/utils.py", line 247, in <genexpr>
    return all(equals(a[key], b[key]) for key in a)
  File "/u/jons/src/DESC/desc/utils.py", line 253, in equals
    return a.eq(b)
  File "/u/jons/src/DESC/desc/io/equilibrium_io.py", line 197, in eq
    return equals(dict1, dict2)
  File "/u/jons/src/DESC/desc/utils.py", line 247, in equals
    return all(equals(a[key], b[key]) for key in a)
  File "/u/jons/src/DESC/desc/utils.py", line 247, in <genexpr>
    return all(equals(a[key], b[key]) for key in a)
  File "/u/jons/src/DESC/desc/utils.py", line 243, in equals
    return np.allclose(a, b)
  File "<__array_function__ internals>", line 6, in allclose
  File "/cobra/u/system/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/numpy/core/numeric.py", line 2159, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "<__array_function__ internals>", line 6, in isclose
  File "/cobra/u/system/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/numpy/core/numeric.py", line 2260, in isclose
    return within_tol(x, y, atol, rtol)
  File "/cobra/u/system/soft/SLE_12/packages/x86_64/anaconda/3/2020.02/lib/python3.7/site-packages/numpy/core/numeric.py", line 2246, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (26,196) (26,130) 
srun: error: co6014: task 0: Exited with exit code 1
srun: Terminating job step 4224776.0
```

Any idea what could go wrong here?

**Comment by f0uriest** [comment]
Should be resolved as of 7a5b2ab, we'll be putting out a new tagged release later today or tomorrow with a few other fixes. Please reopen if it's still an issue
